//
// Created by Mackan on 2026-02-13.
//

#ifndef FADERFLOW_TEST_ICON_DATA_H
#define FADERFLOW_TEST_ICON_DATA_H

// Simple test icon pattern - 64x64 RGB565
// Creates a cyan speaker icon on black background

// RGB565 colors
#define C_BLACK  0x0000
#define C_CYAN   0x07FF

// Generate a simple speaker pattern
// Row 0-19: Black
C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK,
C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK,
C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK,
C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK,


#endif //FADERFLOW_TEST_ICON_DATA_H